
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (1, "SESAB", "SECRETARIA DA SAÚDE");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (2, "SEC", "SECRETARIA DA EDUCAÇÃO");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "ADAB", "Agência de Defesa Agropecuária do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "AGERBA", "Agência Estadual de Regulação de Serviços Públicos de Energia, Transportes e Comunicações do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "AGERSA", "Agência Reguladora de Saneamento Básico do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "Casa Civil", "Casa Civil do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "Casa Militar", "Casa Militar do Governo da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "CEPED", "Centro de Pesquisas e Desenvolvimento do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "DETRAN", "Departamento de Trânsito do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "FAPESB", "Fundação de Amparo à Pesquisa do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "FPC", "Fundação Pedro Calmon");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "FUNCEB", "Fundação Cultural do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "FUNDAC", "Fundação da Criança e do Adolescente");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "Gabinete da Vice Governadoria", "Gabinete da Vice Governadoria do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "Gabinete do Governador", "Gabinete do Governador do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "IBAMETRO", "Instituto Bahiano Metrologia Normalização e Qualidade Industrial");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "INEMA", "Instituto do Meio Ambiente e Recursos Hídricos");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "IPAC", "Instituto do Patrimônio Artistico e Cultural da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "JUCEB", "Junta Comercial do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "OGE", "Ouvidoria Geral do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "PGE", "Procuradoria Geral do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SAEB", "Secretaria do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SDE", "Secretaria do Desenvolvimento Econônmico do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SDR", "Secretaria de Desenvovimento Rural do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEAGRI", "Secretaria da Agricultura, Pecuária, Irrigação, Pesca, e Aquicultura do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEAP", "Secretaria da Administração Penitenciária do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SECOM", "Secretaria da Comunicação Social do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SECTI", "Secretaria de Ciência, Tecnologia e Inovação do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SECULT", "Secretaria de Cultura do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEDUR", "Secretaria DE Desenvolvimento Urbano do Governo do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEFAZ", "Secretaria da Fazenda do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEI", "Superitendência de Estudos Econônicos e Sociais do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEINFRA", "Secretaria de Infraestrutura do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEMA", "Secretaria do Meio Ambiente do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEPLAN", "Secretaria do Planejamento do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEADES", "Secretaria de Assistência e Desenvolvimento Social");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SEPROMI", "Secretaria de Promoção da Igualdade Racial e dos Povos e Comunidades Tradicionais do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SERIN", "Secretaria de Relações Institucionais do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SETRE", "Secretaria do Trabalho Emprego Renda e Esporte do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SETRE-SUDESB", "Superitendência dos Desportos do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SETUR", "Secretaria de Turismo do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SIRH", "Secretaria de Infraestrutura Hídrica e Saneamento do Estado da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SJDH", "Secretaria da Justiça e Direitos Humanos");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SPM", "Secretaria de Política Para Mulheres");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SSP-BOMBEIROS", "Secretaria de Securança Pública/Corpo de Bombeiros");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SSP-DPT", "Secretaria de Securança Publica/D. de Policia Técnica");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SSP-PMBA", "Secretaria de Securança Pública/PMBA");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SSP-Polocia Civil", "Secretaria de Securança Pública/Polocia Civil");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SSP-SEDE-CAB", "Secretaria de Securança Pública/SEDE-CAB");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "SSP-STELECOM", "Secretaria de Securança Pública/STELECOM");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "UEPS", "Universidade Estadual de Feira de Santana");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "UESB", "Universidade Estadual do Sudoeste da Bahia");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "UESC", "Universidade Estadual de Santa Cruz");
INSERT INTO sys.tborgaos (tborgaosidtbConvenio, Sigla, tbOrgaosDescricao) VALUES (3, "UNEB", "Universidade Estadual da Bahia");

