CREATE TABLE `ppeconecao`.`tbtabelageral` (
  `idTabelaGeral` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `TbTabelaGeralMatricula` VARCHAR(10) NOT NULL,
  `TbTabelaGeralNome` VARCHAR(100) NOT NULL,
  `TbTabelaGeralDataAdimissao` DATE NULL,
  `TbTabelaGeralDataDemissao` DATE NULL,
  `TbTabelaGeralNomeMae` VARCHAR(100) NULL,
  `TbTabelaGeralNomePai` VARCHAR(100) NULL,
  `TbTabelaGeralDataNascimento` DATE NULL,
  `TbTabelaGeralSexo` INT NULL,
  `TbTabelaGeralSituacao` VARCHAR(10) NULL,
  `TbTabelaGeralNaturalidade` VARCHAR(45) NULL,
  `TbTabelaGeralNacionalidade` VARCHAR(45) NULL,
  `TbTabelaGeralEstadoCivil` VARCHAR(10) NULL,
  `TbTabelaGeralTipoLogradouro` VARCHAR(100) NULL,
  `TbTabelaGeralBairro` VARCHAR(100) NULL,
  `TbTabelaGeralMunicipio` VARCHAR(100) NULL,
  `TbTabelaGeralEndereco` VARCHAR(100) NULL,
  `TbTabelaGeralCEP` VARCHAR(8) NULL,
  `TbTabelaGeralDDTel` VARCHAR(2) NULL,
  `TbTabelaGeralTelefone` VARCHAR(9) NULL,
  `TbTabelaGeralDDCel` VARCHAR(2) NULL,
  `TbTabelaGeralCelular` VARCHAR(9) NULL,
  `TbTabelaGeralRG` VARCHAR(13) NOT NULL,
  `TbTabelaGeralOrgaoExpedidor` VARCHAR(10) NULL,
  `TbTabelaGeralUFExpedidor` VARCHAR(3) NULL,
  `TbTabelaGeralDataExpedicao` DATETIME NULL,
  `TbTabelaGeralCPF` VARCHAR(13) NOT NULL,
  `TbTabelaGeralCTPS` VARCHAR(10) NOT NULL,
  `TbTabelaGeralSerieCTPS` VARCHAR(5) NOT NULL,
  `TbTabelaGeralDataExpedicaoCTPS` DATETIME NOT NULL,
  `TbTabelaGeralUFCTPS` VARCHAR(5) NOT NULL,
  `TbTabelaGeralTituloDeEleitor` VARCHAR(14) NOT NULL,
  `TbTabelaGeralSecaoTituloDeEleitor` VARCHAR(4) NOT NULL,
  `TbTabelaGeralZonaTituloDeEleitor` VARCHAR(4) NOT NULL,
  `TbTabelaGeralUFTituloEleitor` VARCHAR(3) NOT NULL,
  `TbTabelaGeralPIS` VARCHAR(12) NULL,
  `TbTabelaGeralReservista` VARCHAR(14) NULL,
  `TbTabelaGeralInstrucao` VARCHAR(10) NULL,
  `TbTabelaGeralAgencia` VARCHAR(10) NULL,
  `TbTabelaGeralConta` VARCHAR(10) NULL,
  `TbTabelaGeralFuncao` VARCHAR(100) NULL,
  `TbTabelaGeralPostoDeTrabalho` VARCHAR(100) NULL,
  `TbTabelaGeralSalario` DOUBLE NULL,
  `TbTabelaGeralInsalubridade` INT NULL,
  `TbTabelaGeralEmail01` VARCHAR(100) NULL,
  `TbTabelaGeralEmail02` VARCHAR(100) NULL,
  `TbTabelaGeralTermino1Periodo` VARCHAR(45) NULL,
  `TbTabelaGeralProrrogacao1` DATETIME NULL,
  `TbTabelaGeralTermino` DATETIME NULL,
  `TbTabelaGeralCentroDeCusto` VARCHAR(20) NULL,
  `TbTabelaGeralCBO` VARCHAR(10) NULL,
  `TbTabelaGeralTomadorDoServico` VARCHAR(60) NULL,
  `TbTabelaGeralCNPJTomador` VARCHAR(20) NULL,
  PRIMARY KEY (`idTabelaGeral`, `TbTabelaGeralMatricula`, `TbTabelaGeralRG`, `TbTabelaGeralCPF`, `TbTabelaGeralCTPS`),
  UNIQUE INDEX `idTabelaGeral_UNIQUE` (`idTabelaGeral` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;